name: Demo of Namespace Custom Runner Images

on:
  workflow_dispatch:

jobs:
  apt-install:
    runs-on: namespace-profile-default
    steps:
      - name: Install postgresql-client
        run: sudo apt-get install -y postgresql-client
      - name: Use psql
        run: psql --version

  custom-image:
    runs-on: namespace-profile-custom-image-postgresql
    steps:
      - name: Use psql
        run: psql --version
